#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Apr  2 16:47:28 2024

@author: qchevalier
"""

import pygame
import sys

# Initialisation de Pygame
pygame.init()

# Créer une fenêtre de taille 800x600 pixels
size = width, height = 800, 600
screen = pygame.display.set_mode(size)

# Charger l'image
image = pygame.image.load('plateau.jpg')

# Déterminer la taille maximale de l'image dans la fenêtre
max_width = width * 0.75
max_height = height * 0.75

# Redimensionner l'image en conservant son ratio pour pas qu'elle ne se déforme en fonction de la taille de la fenetre
ratio = min(max_width / image.get_width(), max_height / image.get_height())
new_width = int(image.get_width() * ratio)
new_height = int(image.get_height() * ratio)
nouvelle_image = pygame.transform.scale(image, (new_width, new_height))

# Calculer les coordonnées pour centrer l'image dans la fenêtre
x = (width - new_width) // 2
y = (height - new_height) // 2

#equation de cercle première ligne du bas : (x+5,71)**2 + (y+834,38)**2 = 383679,68 
#eq 2ème ligne : (x-2,8)**2 +(y+387,88)**2 = 66755,15
#eq 3ème ligne : (x-0,77)**2 + (y+464,7)**2 = 87187,35
#coeff directeur segment 4ème ligne : delta = 0,5225

# Boucle principale
running = True
while running:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False

    # Effacer l'écran avec une couleur de fond
    screen.fill((255, 255, 255))  # Blanc

    # Dessiner l'image au centre de la fenêtre
    screen.blit(nouvelle_image, (x, y))

    # Mettre à jour l'affichage
    pygame.display.flip()

# Quitter Pygame
pygame.quit()
sys.exit()
